const uid = require('../util/uid');
const Variable = require('../engine/variable');
const Comment = require('../engine/comment');
const Frame = require('../engine/frame');
const {loadCostume} = require('../import/load-costume');
const {loadSound} = require('../import/load-sound');

const METHODS = [
    'addSprite', 'duplicateSprite', 'deleteSprite', 'renameSprite', 'reorderTarget',
    'addCostume', 'addCostumeFromLibrary', 'duplicateCostume', 'deleteCostume', 'renameCostume',
    'reorderCostume', 'shareCostumeToTarget', 'updateSvg', 'updateBitmap',
    'addSound', 'duplicateSound', 'deleteSound', 'renameSound', 'reorderSound',
    'shareSoundToTarget', 'updateSoundBuffer', 'shareBlocksToTarget', 'postSpriteInfo'
];
const EXTENSIONS = ['loadExtensionURL', 'removeExtension', 'reorderExtension'];
const INDEXED = {
    duplicateCostume: ['costumes', 0],
    deleteCostume: ['costumes', 0],
    renameCostume: ['costumes', 0],
    updateSvg: ['costumes', 0],
    updateBitmap: ['costumes', 0],
    shareCostumeToTarget: ['costumes', 0],
    reorderCostume: ['costumes', 1],
    selectCostume: ['costumes', 0],
    duplicateSound: ['sounds', 0],
    deleteSound: ['sounds', 0],
    renameSound: ['sounds', 0],
    updateSoundBuffer: ['sounds', 0],
    shareSoundToTarget: ['sounds', 0],
    reorderSound: ['sounds', 1]
};
const clone = value => JSON.parse(JSON.stringify(value));
const fields = (value, keys) => Object.fromEntries(keys.filter(key => typeof value[key] !== 'undefined')
    .map(key => [key, value[key]]));
const assetFields = ['name', 'md5', 'assetId', 'dataFormat', 'rotationCenterX', 'rotationCenterY',
    'bitmapResolution', 'rate', 'sampleCount', 'format', 'mwEditId'];
const dictDiff = (before, after) => {
    const changes = {};
    for (const key of new Set([...Object.keys(before || {}), ...Object.keys(after || {})])) {
        if (JSON.stringify(before && before[key]) !== JSON.stringify(after && after[key])) {
            changes[key] = after && Object.prototype.hasOwnProperty.call(after, key) ? after[key] : null;
        }
    }
    return changes;
};

/** VM editing boundary. Only the host executes requests. Every peer consumes
 * the resulting concrete mutations, including IDs generated by native VM code.
 * Runtime notifications are deliberately not editing commands. */
class EditingCommands {
    constructor (vm) {
        this.vm = vm;
        this.handler = null;
        this.originals = {};
        for (const method of METHODS) {
            if (typeof vm[method] !== 'function') continue;
            this.originals[method] = vm[method];
            vm[method] = (...args) => {
                if (!this.handler) return this.originals[method].apply(vm, args);
                return this.request(method, args);
            };
        }
        this.extensions = {};
        for (const method of EXTENSIONS) {
            if (typeof vm.extensionManager[method] !== 'function') continue;
            this.extensions[method] = vm.extensionManager[method].bind(vm.extensionManager);
            vm.extensionManager[method] = (...args) => (this.handler && !this.loadingSnapshot ?
                this.request(method, args) : this.extensions[method](...args));
        }
    }

    request (method, args, targetId) {
        const vm = this.vm;
        let target = targetId ? vm.runtime.getTargetById(targetId) : vm.editingTarget;
        if (method === 'postSpriteInfo' && vm._dragTarget) target = vm._dragTarget;
        if (method === 'reorderTarget') target = vm.runtime.targets[args[0]];
        if (['reorderCostume', 'reorderSound'].includes(method)) target = vm.runtime.getTargetById(args[0]);
        const command = {method, args, targetId: target ? target.id : null};
        if (method === 'reorderTarget') {
            const without = vm.runtime.targets.filter(item => item !== target);
            command.beforeTargetId = without[args[1]] ? without[args[1]].id : null;
        }
        let restore;
        if (method === 'deleteCostume' && target.getCostumes().length <= 1) return null;
        if (method === 'deleteCostume' || method === 'deleteSound') {
            const isCostume = method === 'deleteCostume';
            const item = Object.assign({}, target.sprite[isCostume ? 'costumes' : 'sounds'][args[0]]);
            delete item.mwEditId;
            restore = () => this.request(isCostume ? 'addCostume' : 'addSound',
                isCostume ? [item.md5, item, target.id] : [item, target.id], target.id);
        } else if (method === 'deleteSprite') {
            const sprite = vm.exportSprite(args[0], 'arraybuffer');
            restore = () => sprite.then(bytes => this.request('addSprite', [bytes]));
        }
        if (INDEXED[method]) {
            const [list, index] = INDEXED[method];
            const item = target && target.sprite[list][args[index]];
            if (!item) return Promise.reject(new Error('The selected item no longer exists.'));
            command.itemId = item.mwEditId;
            if (method.startsWith('reorder')) {
                const without = target.sprite[list].filter(entry => entry !== item);
                command.beforeId = without[args[2]] ? without[args[2]].mwEditId : null;
            }
        }
        // Surface failures even for legacy UI callers which don't await void methods.
        let result;
        try {
            result = Promise.resolve(this.handler(command));
        } catch (error) {
            result = Promise.reject(error);
        }
        result.catch(error => vm.emit('EDIT_COMMAND_ERROR', error));
        return restore || result;
    }

    targetState (target, includeCode = true) {
        for (const list of ['costumes', 'sounds']) {
            for (const item of target.sprite[list]) if (!item.mwEditId) item.mwEditId = uid();
        }
        return clone({
            id: target.id,
            name: target.getName(),
            isStage: Boolean(target.isStage),
            props: fields(target, ['x', 'y', 'direction', 'size', 'visible',
                'rotationStyle', 'draggable', 'currentCostume']),
            ...(includeCode ? {blocks: target.blocks._blocks,
                variables: target.variables,
                comments: target.comments,
                frames: target.frames || {}} : {}),
            costumes: target.getCostumes().map(item => fields(item, assetFields)),
            sounds: target.getSounds().map(item => fields(item, assetFields))
        });
    }

    snapshot (includeCode = true, targetId = null) {
        return this.vm.runtime.targets.filter(target => target.isOriginal && (!targetId || target.id === targetId))
            .map(target => this.targetState(target, includeCode));
    }

    context (target) {
        const vm = this.vm;
        const context = Object.create(vm);
        context.editingTarget = target;
        context._dragTarget = null;
        context._editCommandContext = true;
        context.extensionManager = Object.create(vm.extensionManager);
        for (const method of Object.keys(this.extensions)) context.extensionManager[method] = this.extensions[method];
        context.emitTargetsUpdate = () => {};
        context.emitWorkspaceUpdate = () => {};
        context.setEditingTarget = id => {
            context.editingTarget = vm.runtime.getTargetById(id);
        };
        // Internal method calls must never submit a second command.
        for (const method of Object.keys(this.originals)) context[method] = this.originals[method].bind(context);
        return context;
    }

    async execute (command, active = () => true) {
        const {method} = command;
        if (!METHODS.includes(method) && !EXTENSIONS.includes(method) &&
            method !== 'blockEvent' && method !== 'selectCostume') throw new Error('Unknown editing command');
        const vm = this.vm;
        const includeCode = ['blockEvent', 'shareBlocksToTarget', 'addSprite', 'duplicateSprite',
            'deleteSprite', 'renameSprite', ...EXTENSIONS].includes(method);
        const onlyTarget = method === 'blockEvent' && !command.args[0].type.startsWith('var_') ?
            command.targetId : null;
        const before = this.snapshot(includeCode, onlyTarget);
        const target = command.targetId ? vm.runtime.getTargetById(command.targetId) : null;
        const args = command.args.slice();
        if (method === 'reorderTarget') {
            args[0] = vm.runtime.targets.findIndex(item => item.id === command.targetId);
            if (args[0] < 0) throw new Error('The sprite was deleted by another editor.');
            const without = vm.runtime.targets.filter(item => item.id !== command.targetId);
            const next = without.findIndex(item => item.id === command.beforeTargetId);
            args[1] = next < 0 ? without.length : next;
        }
        if (INDEXED[method]) {
            const [list, position] = INDEXED[method];
            const items = target && target.sprite[list];
            const index = items ? items.findIndex(item => item.mwEditId === command.itemId) : -1;
            if (index < 0) throw new Error('The item was deleted by another editor.');
            args[position] = index;
            if (method.startsWith('reorder')) {
                const without = items.filter((item, i) => i !== index);
                const next = without.findIndex(item => item.mwEditId === command.beforeId);
                args[2] = next < 0 ? without.length : next;
            }
        }
        const context = this.context(target);
        context._editCommandActive = active;
        if (method === 'blockEvent') {
            if (!target) throw new Error('The sprite was deleted by another editor.');
            const event = args[0];
            if (typeof event.xml === 'string') event.xml = {outerHTML: event.xml};
            if (event.type === 'move') {
                const block = target.blocks.getBlock(event.blockId);
                if (!block) throw new Error('The block was deleted by another editor.');
                delete event.oldParentId;
                delete event.oldInputName;
                if (block.parent) {
                    event.oldParentId = block.parent;
                    const parent = target.blocks.getBlock(block.parent);
                    const input = parent && Object.values(parent.inputs).find(item => item.block === block.id);
                    if (input) event.oldInputName = input.name;
                }
                if (event.newParentId) {
                    const parent = target.blocks.getBlock(event.newParentId);
                    if (!parent) throw new Error('The destination block was deleted by another editor.');
                    // The destination may have been occupied since this request
                    // was made. Preserve that script by detaching it first.
                    const input = event.newInputName && parent.inputs[event.newInputName];
                    const occupiedId = event.newInputName ? input && input.block : parent.next;
                    const occupied = occupiedId && target.blocks.getBlock(occupiedId);
                    if (occupied && occupied.id !== block.id && !occupied.shadow) {
                        target.blocks.moveBlock({id: occupied.id,
                            oldParent: parent.id,
                            oldInput: event.newInputName,
                            newCoordinate: {x: 0, y: 0}});
                    }
                }
            }
            // blocks.blocklyListen consumes a plain VM event, not a Blockly instance.
            const getTarget = vm.runtime.getEditingTarget;
            vm.runtime.getEditingTarget = () => target;
            try {
                target.blocks.blocklyListen(event);
            } finally {
                vm.runtime.getEditingTarget = getTarget;
            }
        } else if (method === 'selectCostume') {
            target.setCostume(args[0]);
        } else if (EXTENSIONS.includes(method)) {
            await this.extensions[method](...args);
        } else {
            await context[method](...args);
            const seen = new Set();
            for (const itemTarget of vm.runtime.targets.filter(item => item.isOriginal)) {
                for (const item of [...itemTarget.getCostumes(), ...itemTarget.getSounds()]) {
                    if (!item.mwEditId || seen.has(item.mwEditId)) item.mwEditId = uid();
                    seen.add(item.mwEditId);
                }
            }
        }
        if (!active()) throw new Error('Editing session ended');
        const after = this.snapshot(includeCode, onlyTarget);
        const patches = [];
        for (const state of after) {
            const old = before.find(item => item.id === state.id);
            if (!old) {
                patches.push({id: state.id,
                    create: JSON.parse(vm.toJSON(state.id, {allowOptimization: false})),
                    state});
                continue;
            }
            const patch = {id: state.id};
            for (const key of ['blocks', 'variables', 'comments', 'frames', 'props']) {
                const diff = dictDiff(old[key], state[key]);
                if (Object.keys(diff).length) patch[key] = diff;
            }
            for (const key of ['name', 'costumes', 'sounds']) {
                if (JSON.stringify(old[key]) !== JSON.stringify(state[key])) patch[key] = state[key];
            }
            if (Object.keys(patch).length > 1) patches.push(patch);
        }
        for (const state of before) {
            if (!after.some(item => item.id === state.id)) patches.push({id: state.id, deleted: true});
        }
        const assetRefs = new Set();
        for (const patch of patches) {
            const state = patch.state || patch;
            for (const item of [...(state.costumes || []), ...(state.sounds || [])]) {
                if (item.md5) assetRefs.add(item.md5);
            }
        }
        const result = {patches,
            order: vm.runtime.targets.filter(item => item.isOriginal).map(item => item.id),
            assetRefs: Array.from(assetRefs)};
        if (EXTENSIONS.includes(method)) result.extension = {method, args};
        this.refresh(patches);
        return result;
    }

    refresh (patches) {
        const vm = this.vm;
        if (vm.editingTarget && !vm.runtime.getTargetById(vm.editingTarget.id)) {
            vm.editingTarget = vm.runtime.targets.find(target => target.isOriginal && !target.isStage) ||
                vm.runtime.getTargetForStage();
            vm.runtime.setEditingTarget(vm.editingTarget);
        }
        vm.emitTargetsUpdate(false);
        if (vm.editingTarget && patches.some(patch =>
            (patch.id === vm.editingTarget.id && (patch.blocks || patch.comments || patch.frames || patch.state)) ||
            patch.variables)) {
            if (this.deferRefresh) this.refreshPending = true;
            else vm.emitWorkspaceUpdate();
        }
        vm.runtime.emitProjectChanged();
    }

    async apply (result, getAsset, active = () => true) {
        const vm = this.vm;
        for (const patch of result.patches) {
            if (!active()) throw new Error('Editing session ended');
            let target = vm.runtime.getTargetById(patch.id);
            if (patch.deleted) {
                if (target) this.originals.deleteSprite.call(this.context(target), patch.id);
                continue;
            }
            if (patch.create && !target) {
                // A zip supplies bytes directly to the VM importer, without relying on a storage web fetch.
                const zip = new vm.exports.JSZip();
                zip.file('sprite.json', JSON.stringify(patch.create));
                for (const item of [...patch.state.costumes, ...patch.state.sounds]) {
                    const asset = getAsset(item.md5);
                    if (!asset) throw new Error(`Missing asset ${item.md5}`);
                    zip.file(item.md5, asset.data);
                }
                const buffer = await zip.generateAsync({type: 'arraybuffer'});
                if (!active()) throw new Error('Editing session ended');
                const context = this.context(vm.editingTarget);
                context._editCommandActive = active;
                await this.originals.addSprite.call(context, buffer);
                target = context.editingTarget;
                target.id = patch.id;
            }
            if (!target) throw new Error(`Missing target ${patch.id}`);
            await this.applyState(target, patch.state || patch, getAsset, active);
        }
        if (result.extension) {
            if (!active()) throw new Error('Editing session ended');
            await this.extensions[result.extension.method](...result.extension.args);
        }
        if (!active()) throw new Error('Editing session ended');
        const order = new Map(result.order.map((id, index) => [id, index]));
        vm.runtime.targets.sort((a, b) => (order.get(a.id) || 0) - (order.get(b.id) || 0));
        this.refresh(result.patches);
    }

    // Session commands own the mutation queue for the duration of asset decoding.
    /* eslint-disable require-atomic-updates */
    async applyState (target, state, getAsset, active = () => true) {
        for (const list of ['costumes', 'sounds']) {
            if (!state[list]) continue;
            const loaded = [];
            for (const descriptor of state[list]) {
                let item = target.sprite[list].find(old =>
                    (!old.mwEditId || old.mwEditId === descriptor.mwEditId) && old.md5 === descriptor.md5);
                if (item) {
                    Object.assign(item, descriptor);
                } else {
                    item = Object.assign({}, descriptor);
                    item.asset = getAsset(item.md5);
                    if (!item.asset) throw new Error(`Missing asset ${item.md5}`);
                    if (list === 'costumes') await loadCostume(item.md5, item, this.vm.runtime);
                    else await loadSound(item, this.vm.runtime, target.sprite.soundBank);
                    if (item.md5 !== descriptor.md5) throw new Error(`Could not decode asset ${descriptor.md5}`);
                    Object.assign(item, descriptor);
                }
                if (!active()) throw new Error('Editing session ended');
                loaded.push(item);
            }
            target.sprite[list] = loaded;
        }
        if (!active()) throw new Error('Editing session ended');
        for (const key of ['variables', 'comments', 'frames']) {
            if (!state[key]) continue;
            if (!target[key] || typeof state.isStage !== 'undefined') target[key] = Object.create(null);
            for (const [id, value] of Object.entries(state[key])) {
                if (value === null) {
                    delete target[key][id]; continue;
                }
                const prototype = key === 'variables' ? Variable.prototype :
                    key === 'comments' ? Comment.prototype : Frame.prototype;
                target[key][id] = Object.assign(Object.create(prototype), value);
            }
        }
        if (state.blocks) {
            if (typeof state.isStage !== 'undefined') target.blocks._blocks = Object.create(null);
            for (const [id, block] of Object.entries(state.blocks)) {
                if (block === null) delete target.blocks._blocks[id];
                else target.blocks._blocks[id] = clone(block);
            }
            target.blocks._scripts = Object.keys(target.blocks._blocks)
                .filter(id => target.blocks._blocks[id].topLevel);
            target.blocks.resetCache();
        }
        if (typeof state.name === 'string') target.sprite.name = state.name;
        const props = state.props || {};
        if ('x' in props || 'y' in props) {
            target.setXY(typeof props.x === 'undefined' ? target.x : props.x,
                typeof props.y === 'undefined' ? target.y : props.y);
        }
        for (const [key, method] of Object.entries({direction: 'setDirection',
            size: 'setSize',
            visible: 'setVisible',
            rotationStyle: 'setRotationStyle',
            draggable: 'setDraggable',
            currentCostume: 'setCostume'})) {
            if (key in props) target[method](props[key]);
        }
        if (state.costumes) target.setCostume(target.currentCostume);
    }
}

module.exports = EditingCommands;
module.exports.METHODS = METHODS;
module.exports.EXTENSIONS = EXTENSIONS;
